New Loader code based on upstream 1.3.268 compared against upstream
KhronosGroup/VulkanSC-Loader pull request #15
Opened 2023-11-09 08:29 UTC by aqnuep

NOTE: This PR is for review purposes only as this branch will replace `sc_main`, and not expected to be merged into `main` (upstream baseline code).

2023-11-22 21:22 UTC, dgkoch requested changes

2023-11-23 08:17 UTC, aqnuep commented on CMakeLists.txt
> +set(VULKANSC OFF CACHE BOOL "User defined variable for VULKANSC mode to be passed in through cmake command line e.g. -DVULKANSC=ON")
Sure. It does not make an effective difference as of now (CMake is a weird mixture of declarative and imperative languages), but better safe than sorry.

2023-11-23 08:20 UTC, aqnuep commented on CMakeLists.txt
> +    option(BUILD_WSI_SCI_SUPPORT "Build SCI WSI support" OFF)
Good catch! I'm not sure how I missed that.

2023-11-23 08:22 UTC, aqnuep commented on loader/loader.c
> +            }
Oh yes!

This was the loader bug which caused `vkCreateInstance` to always return `VK_SUCCESS` if the application passes in any extensions in the create info, even if things actually failed.

This fix has already been upstreamed and should "come back" at the next downstreaming.

2023-11-29 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/VulkanSC-Loader?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/VulkanSC-Loader?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/VulkanSC-Loader?pullRequest=15) it.</sub>

2023-11-29 12:25 UTC, aqnuep commented
I've downstreamed 1.3.271, which introduced some changes to QNX builds as upstream now uses dedicated makefiles for the purpose, but I've kept CMake support as far as possible downstream.

2023-12-03 14:06 UTC, aqnuep commented
Closing this PR now that the code in `sc_main` subsumes it. @sricker-nvidia, please use the code in `sc_main` for IHV testing purposes.

2023-12-03 14:06 UTC, closed without merging